export const GameViewId = {
    MISSION_POPUP_GOAL: "MISSION_POPUP_GOAL",
    MISSION_POPUP_CLOSE: "MISSION_POPUP_CLOSE",
    REELS_COINS: "REELS_COINS",
    SPIN_BUTTON: "SPIN_BUTTON",
    INVENTORY_BUTTON: "INVENTORY_BUTTON",
    ENCYCLOPEDIA_BUTTON: "ENCYCLOPEDIA_BUTTON",
    SETTINGS_BUTTON: "SETTINGS_BUTTON",

    ADD_SYMBOL_POPUP_TITLE: "ADD_SYMBOL_POPUP_TITLE",
    ADD_SYMBOL_POPUP_SYMBOLS: "ADD_SYMBOL_POPUP_SYMBOLS",
    ADD_SYMBOL_POPUP_SYMBOLS_REROLLS: "ADD_SYMBOL_POPUP_SYMBOLS_REROLLS",
    ADD_SYMBOL_POPUP_FIRST_SYMBOL: "ADD_SYMBOL_POPUP_FIRST_SYMBOL",
    ADD_SYMBOL_POPUP_FIRST_SYMBOL_VALUE: "ADD_SYMBOL_POPUP_FIRST_SYMBOL_VALUE",
    ADD_SYMBOL_POPUP_FIRST_SYMBOL_DESC: "ADD_SYMBOL_POPUP_FIRST_SYMBOL_DESC",
    ADD_SYMBOL_POPUP_CLOSE_BUTTON: "ADD_SYMBOL_POPUP_CLOSE_BUTTON",

    MISSION_BONUS_POPUP_BONUSES: "MISSION_BONUS_POPUP_BONUSES",

    // INVENTORY_POPUP_REMOVES: "INVENTORY_POPUP_REMOVES",
    INVENTORY_POPUP_FIRST_SYMBOL: "INVENTORY_POPUP_FIRST_SYMBOL",
    INVENTORY_POPUP_SYMBOL: "INVENTORY_POPUP_SYMBOL",
    INVENTORY_POPUP_CLOSE: "INVENTORY_POPUP_CLOSE",

    // INVENTORY_POPUP_FIRST_SYMBOL_REMOVE: "INVENTORY_POPUP_FIRST_SYMBOL_REMOVE"
    COMPANION_INFO_POPUP_REMOVE: "COMPANION_INFO_POPUP_REMOVE",
    COMPANION_INFO_POPUP_CLOSE: "COMPANION_INFO_POPUP_CLOSE",

    CONFIG_INFO_POPUP_CLOSE: "CONFIG_INFO_POPUP_CLOSE",

    ENCYCLOPEDIA_POPUP_SYMBOL: "ENCYCLOPEDIA_POPUP_SYMBOL",
    ENCYCLOPEDIA_POPUP_CLOSE: "ENCYCLOPEDIA_POPUP_CLOSE",

    SETTINGS_POPUP_CLOSE: "SETTINGS_POPUP_CLOSE",
    SETTINGS_POPUP_SOUND: "SETTINGS_POPUP_SOUND",

    GAME_OVER_POPUP_CLOSE: "GAME_OVER_POPUP_CLOSE",
}